/**
 * Built-in slide graphics (drawn in the app from icons, in the deck's colours). AI picks one by key
 * for each slide so decks have pictures without any image search. Keep in step with web/src/components/slides/graphics.tsx.
 */
export const SLIDE_ICONS = [
  'bolt',
  'bulb',
  'battery',
  'plug',
  'switch',
  'chip',
  'robot',
  'code',
  'computer',
  'phone',
  'wifi',
  'gear',
  'tools',
  'science',
  'microscope',
  'flower',
  'tree',
  'leaf',
  'grass',
  'farm',
  'water',
  'waves',
  'sun',
  'cloud',
  'storm',
  'air',
  'earth',
  'rocket',
  'star',
  'moon',
  'calculate',
  'ruler',
  'shapes',
  'chart',
  'insights',
  'clock',
  'timer',
  'speed',
  'scale',
  'map',
  'compass',
  'book',
  'school',
  'pencil',
  'idea',
  'question',
  'check',
  'warning',
  'heart',
  'food',
  'animal',
  'bug',
  'car',
  'bus',
  'bike',
  'train',
  'plane',
  'home',
  'factory',
  'recycle',
  'fire',
  'thermometer',
  'sound',
  'music',
  'camera',
  'eye',
  'hand',
  'people',
  'person',
  'brain',
  'shield',
  'lock',
  'money',
  'trophy',
  'flag',
  'puzzle',
  'target',
  'network',
  'cable',
  'solar',
  'wind',
  'sensor',
  'terminal',
  'paint',
  'palette',
  'cricket',
] as const;

const SYN: [RegExp, (typeof SLIDE_ICONS)[number]][] = [
  [/bulb|light|lamp|idea/i, 'bulb'],
  [/batter|cell\b/i, 'battery'],
  [/switch|on\/off|toggle/i, 'switch'],
  [/wire|cable|connect/i, 'cable'],
  [/circuit|chip|electronic|sensor/i, 'chip'],
  [/electric|current|volt|energy|charge|power/i, 'bolt'],
  [/robot|motor|servo|arduino/i, 'robot'],
  [/code|program|algorithm|loop|scratch|python/i, 'code'],
  [/computer|laptop|screen/i, 'computer'],
  [/plant|seed|flower|photosynth/i, 'flower'],
  [/tree|forest/i, 'tree'],
  [/water|rain|river|ocean/i, 'water'],
  [/sun|solar|heat|light energy/i, 'sun'],
  [/planet|earth|world|globe/i, 'earth'],
  [/space|rocket|moon|star/i, 'rocket'],
  [/number|math|add|multipl|fraction|calculat/i, 'calculate'],
  [/measure|length|ruler/i, 'ruler'],
  [/shape|triangle|circle|geometry/i, 'shapes'],
  [/graph|chart|data|survey/i, 'chart'],
  [/time|clock|hour/i, 'clock'],
  [/experiment|test|lab|science/i, 'science'],
  [/safe|safety|danger|careful/i, 'shield'],
  [/question|why|how|what/i, 'question'],
  [/recap|summary|remember|review/i, 'check'],
  [/team|group|friends|partner|share/i, 'people'],
  [/think|brain|mind|memory/i, 'brain'],
  [/animal|bird|insect|pet/i, 'animal'],
  [/food|eat|fruit|vegetable|nutri/i, 'food'],
  [/recycl|waste|environment|pollut/i, 'recycle'],
  [/sound|hear|music/i, 'sound'],
  [/goal|aim|objective|learn/i, 'target'],
  [/build|make|create|design|tool/i, 'tools'],
];

/** Guess a fitting graphic from slide text (used offline and when the AI leaves one out). */
export function guessIcon(text: string, fallback: (typeof SLIDE_ICONS)[number] = 'idea') {
  for (const [re, k] of SYN) if (re.test(text)) return k;
  return fallback;
}
